services:
  postgres16-service:
    image: postgres:16.1
    container_name: postgres16-container
    volumes:
      - postgres_data:/var/lib/postgresql
    restart: always
    environment:
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"

volumes:
  postgres_data: {}